/**
 * PDF Report Generator
 *
 * Uses PDFKit to generate professional-looking reports:
 *
 *   1. Case Summary     — overview of a case and its evidence
 *   2. Chain of Custody — legal chain-of-custody document for one evidence item
 *
 * PDFKit streams directly to the response — no temp files needed.
 */

const PDFDocument = require('pdfkit');
const { generateEvidenceQRCode } = require('./qrcode.util');
const { formatFileSize } = require('./file.util');
const { logger } = require('./logger');

// ─── Constants ───────────────────────────────────────────────────────────────

const COLORS = {
  primary:    '#1a365d',  // Dark navy
  accent:     '#2b6cb0',  // Medium blue
  text:       '#2d3748',  // Dark grey
  muted:      '#718096',  // Medium grey
  border:     '#e2e8f0',  // Light grey
  success:    '#276749',  // Dark green
  danger:     '#c53030',  // Dark red
  warning:    '#c05621'   // Dark orange
};

const FONTS = {
  heading:   'Helvetica-Bold',
  body:      'Helvetica',
  mono:      'Courier'
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

function formatDate(date) {
  if (!date) return 'N/A';
  return new Date(date).toLocaleString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit', second: '2-digit',
    timeZoneName: 'short'
  });
}

function addPageHeader(doc, title, subtitle = '') {
  // Blue header bar
  doc.rect(0, 0, doc.page.width, 80).fill(COLORS.primary);

  doc.fillColor('#ffffff')
     .font(FONTS.heading).fontSize(20)
     .text('🔒 Digital Evidence Vault', 40, 20);

  doc.font(FONTS.body).fontSize(11)
     .text(title, 40, 45);

  if (subtitle) {
    doc.fontSize(9).text(subtitle, 40, 60);
  }

  // Reset colour after header
  doc.fillColor(COLORS.text);
  doc.moveDown(4);
}

function addSectionTitle(doc, text) {
  doc.moveDown(0.5);
  doc.rect(40, doc.y, doc.page.width - 80, 24)
     .fill(COLORS.accent);

  doc.fillColor('#ffffff')
     .font(FONTS.heading).fontSize(11)
     .text(text, 50, doc.y - 18);

  doc.fillColor(COLORS.text);
  doc.moveDown(1);
}

function addRow(doc, label, value, mono = false) {
  const startX = 40;
  const labelW = 160;

  doc.font(FONTS.body).fontSize(9).fillColor(COLORS.muted)
     .text(label, startX, doc.y, { continued: false, width: labelW });

  doc.font(mono ? FONTS.mono : FONTS.body).fontSize(9).fillColor(COLORS.text)
     .text(String(value || 'N/A'), startX + labelW, doc.y - doc.currentLineHeight(), {
       width: doc.page.width - startX - labelW - 40
     });

  // Thin divider
  doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y)
     .strokeColor(COLORS.border).lineWidth(0.5).stroke();
  doc.moveDown(0.4);
}

function addPageFooter(doc, reportType, generatedAt) {
  const pageRange = doc.bufferedPageRange();
  for (let i = 0; i < pageRange.count; i++) {
    doc.switchToPage(pageRange.start + i);
    doc.font(FONTS.body).fontSize(8).fillColor(COLORS.muted)
       .text(
         `${reportType}  |  Generated: ${generatedAt}  |  Page ${i + 1} of ${pageRange.count}`,
         40,
         doc.page.height - 30,
         { width: doc.page.width - 80, align: 'center' }
       );
  }
}

// ─── Case Summary Report ─────────────────────────────────────────────────────

/**
 * Generate a Case Summary PDF.
 *
 * @param {Object} caseData     - Full case object with evidence and user relations
 * @param {Object} generatedBy  - User generating the report { name, email }
 * @returns {Promise<PDFDocument>}  - Flowing PDFKit document (pipe to res)
 */
async function generateCaseSummaryPDF(caseData, generatedBy) {
  const doc = new PDFDocument({ margin: 40, bufferPages: true });
  const generatedAt = formatDate(new Date());

  addPageHeader(
    doc,
    `Case Report: ${caseData.caseNumber}`,
    `Generated by ${generatedBy.name} on ${generatedAt}`
  );

  // ── Case Details ──
  addSectionTitle(doc, 'Case Information');
  addRow(doc, 'Case Number',    caseData.caseNumber);
  addRow(doc, 'Title',          caseData.title);
  addRow(doc, 'Status',         caseData.status);
  addRow(doc, 'Priority',       `${caseData.priority} (1=Critical, 5=Low)`);
  addRow(doc, 'Created By',     caseData.createdBy?.name || 'N/A');
  addRow(doc, 'Created At',     formatDate(caseData.createdAt));
  addRow(doc, 'Assigned To',    caseData.assignedInvestigator?.name || 'Unassigned');
  addRow(doc, 'Closed At',      caseData.closedAt ? formatDate(caseData.closedAt) : '—');

  if (caseData.description) {
    doc.moveDown(0.5);
    doc.font(FONTS.body).fontSize(9).fillColor(COLORS.muted).text('Description:');
    doc.font(FONTS.body).fontSize(9).fillColor(COLORS.text)
       .text(caseData.description, { width: doc.page.width - 80 });
  }

  // ── Evidence Inventory ──
  const evidence = caseData.evidence || [];
  doc.addPage();
  addPageHeader(doc, 'Evidence Inventory', caseData.caseNumber);
  addSectionTitle(doc, `Evidence Items (${evidence.length})`);

  if (evidence.length === 0) {
    doc.font(FONTS.body).fontSize(9).fillColor(COLORS.muted)
       .text('No evidence items found for this case.', { align: 'center' });
  } else {
    for (const [i, ev] of evidence.entries()) {
      if (doc.y > doc.page.height - 200) doc.addPage();

      doc.font(FONTS.heading).fontSize(10).fillColor(COLORS.accent)
         .text(`${i + 1}. ${ev.originalName}`);
      doc.moveDown(0.2);

      addRow(doc, 'Evidence ID',    ev.id, true);
      addRow(doc, 'File Type',      ev.fileType);
      addRow(doc, 'Size',           formatFileSize(ev.fileSize));
      addRow(doc, 'Status',         ev.status);
      addRow(doc, 'SHA-256 Hash',   ev.sha256Hash, true);
      addRow(doc, 'Uploaded At',    formatDate(ev.uploadedAt));
      addRow(doc, 'Uploaded By',    ev.uploadedBy?.name || 'N/A');

      if (ev.status === 'REJECTED' && ev.rejectReason) {
        addRow(doc, 'Reject Reason', ev.rejectReason);
      }

      // QR Code for the evidence item
      try {
        const qrBuffer = await generateEvidenceQRCode(ev);
        doc.image(qrBuffer, doc.page.width - 120, doc.y - 110, { width: 80 });
      } catch (e) {
        // Non-fatal — skip QR if it fails
      }

      doc.moveDown(1);
    }
  }

  addPageFooter(doc, 'Case Summary Report', generatedAt);
  doc.end();

  logger.info('Case summary PDF generated', { caseId: caseData.id, evidenceCount: evidence.length });
  return doc;
}

// ─── Chain of Custody Report ─────────────────────────────────────────────────

/**
 * Generate a Chain of Custody PDF for a single evidence item.
 * This is the legally-admissible custody document.
 *
 * @param {Object} evidenceData  - Evidence record
 * @param {Array}  auditLogs     - All audit log entries for this evidence (chron. order)
 * @param {Object} generatedBy
 * @returns {Promise<PDFDocument>}
 */
async function generateChainOfCustodyPDF(evidenceData, auditLogs, generatedBy) {
  const doc = new PDFDocument({ margin: 40, bufferPages: true });
  const generatedAt = formatDate(new Date());

  addPageHeader(
    doc,
    'Chain of Custody Report',
    `Evidence: ${evidenceData.originalName}  |  Generated by ${generatedBy.name}`
  );

  // ── Legal Notice ──
  doc.rect(40, doc.y, doc.page.width - 80, 40)
     .strokeColor(COLORS.warning).lineWidth(1).stroke();
  doc.font(FONTS.body).fontSize(8).fillColor(COLORS.warning)
     .text(
       'LEGAL NOTICE: This document constitutes an official chain of custody record. '
       + 'Any alteration of this document may constitute obstruction of justice.',
       48, doc.y - 32,
       { width: doc.page.width - 96 }
     );
  doc.fillColor(COLORS.text).moveDown(2);

  // ── Evidence Details ──
  addSectionTitle(doc, 'Evidence Details');
  addRow(doc, 'Evidence ID',    evidenceData.id, true);
  addRow(doc, 'Original Name',  evidenceData.originalName);
  addRow(doc, 'File Type',      evidenceData.fileType);
  addRow(doc, 'File Size',      formatFileSize(evidenceData.fileSize));
  addRow(doc, 'SHA-256 Hash',   evidenceData.sha256Hash, true);
  addRow(doc, 'Case',           evidenceData.case?.caseNumber || 'N/A');
  addRow(doc, 'Upload Date',    formatDate(evidenceData.uploadedAt));
  addRow(doc, 'Current Status', evidenceData.status);
  addRow(doc, 'Encrypted',      evidenceData.isEncrypted ? 'Yes (AES-256-GCM)' : 'No');

  // QR Code
  try {
    const qrBuffer = await generateEvidenceQRCode(evidenceData);
    addSectionTitle(doc, 'Verification QR Code');
    doc.image(qrBuffer, (doc.page.width - 150) / 2, doc.y, { width: 150 });
    doc.moveDown(7);
    doc.font(FONTS.body).fontSize(8).fillColor(COLORS.muted)
       .text('Scan to verify integrity online', { align: 'center' });
    doc.moveDown(1);
  } catch (e) {
    // Skip QR if it fails
  }

  // ── Custody Log Table ──
  doc.addPage();
  addPageHeader(doc, 'Custody Event Log', `${auditLogs.length} events recorded`);
  addSectionTitle(doc, 'Chronological Event Log');

  // Table header
  const colX = [40, 160, 290, 360, 440];
  const colW = [120, 130, 70,  80,  115];
  const headers = ['Timestamp', 'Action', 'Entity', 'User', 'IP Address'];

  doc.rect(40, doc.y, doc.page.width - 80, 18).fill(COLORS.primary);
  headers.forEach((h, i) => {
    doc.font(FONTS.heading).fontSize(8).fillColor('#ffffff')
       .text(h, colX[i], doc.y - 14, { width: colW[i] });
  });
  doc.fillColor(COLORS.text).moveDown(0.3);

  for (const [idx, log] of auditLogs.entries()) {
    if (doc.y > doc.page.height - 80) {
      doc.addPage();
      addPageHeader(doc, 'Custody Event Log (continued)', '');
    }

    const rowColor = idx % 2 === 0 ? '#f7fafc' : '#ffffff';
    doc.rect(40, doc.y, doc.page.width - 80, 18).fill(rowColor);

    const cells = [
      new Date(log.timestamp).toISOString().replace('T', ' ').slice(0, 19),
      log.action,
      log.entity,
      log.user?.name || 'System',
      log.ipAddress || '—'
    ];

    cells.forEach((cell, i) => {
      doc.font(i === 1 ? FONTS.heading : FONTS.body)
         .fontSize(7.5).fillColor(COLORS.text)
         .text(String(cell), colX[i], doc.y - 14, {
           width: colW[i] - 4,
           ellipsis: true
         });
    });

    doc.fillColor(COLORS.text).moveDown(0.3);
  }

  // ── Sign-off Section ──
  doc.addPage();
  addPageHeader(doc, 'Custody Certification', '');
  addSectionTitle(doc, 'Report Certification');

  doc.font(FONTS.body).fontSize(10).fillColor(COLORS.text)
     .text(
       `This chain of custody report was generated on ${generatedAt} by `
       + `${generatedBy.name} (${generatedBy.email}).\n\n`
       + `Total custody events recorded: ${auditLogs.length}\n`
       + `Report generated by: Digital Evidence Vault v1.0.0\n\n`
       + `I certify that the information in this report accurately reflects the `
       + `handling of the above-referenced digital evidence.`,
       { width: doc.page.width - 80 }
     );

  doc.moveDown(4);

  // Signature lines
  const sigY = doc.y;
  doc.moveTo(40, sigY + 40).lineTo(220, sigY + 40).stroke();
  doc.moveTo(280, sigY + 40).lineTo(460, sigY + 40).stroke();

  doc.font(FONTS.body).fontSize(8).fillColor(COLORS.muted)
     .text('Signature', 40, sigY + 44)
     .text('Date', 280, sigY + 44);

  addPageFooter(doc, 'Chain of Custody Report', generatedAt);
  doc.end();

  logger.info('Chain of custody PDF generated', {
    evidenceId: evidenceData.id,
    eventCount: auditLogs.length
  });
  return doc;
}

module.exports = {
  generateCaseSummaryPDF,
  generateChainOfCustodyPDF
};
